# Generated by Django 4.2.5 on 2023-10-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(choices=[('NEW', 'New'), ('ATTO_CHANNELER ', 'Atto channeler'), ('Weeb', 'Weeb'), ('Grand Weeb', 'Grand weeb'), ('ADMIN', '@Admin@')], default='NEW', max_length=15),
        ),
    ]
