# Generated by Django 4.2.5 on 2023-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(choices=[('New', 'NW'), ('ATTO_CHANNELER', 'AR'), ('Weeb', 'WB'), ('-Grand Weeb-', 'GW'), ('@ADMIN@', 'AA')], default='New', max_length=15),
        ),
    ]
