# Generated by Django 4.2.5 on 2023-10-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rank_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
