# Generated by Django 4.2.5 on 2023-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_news_options_alter_news_author_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type_of_message',
            field=models.CharField(choices=[('A', 'Anonymous'), ('H', 'Hybrid'), ('P', 'Public')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=1, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name of article'),
        ),
    ]
