# Generated by Django 4.2.5 on 2023-10-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.threads', verbose_name='thread'),
        ),
    ]
