# Generated by Django 4.2.5 on 2023-10-10 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_news_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
