# Generated by Django 4.2.5 on 2023-10-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Text'),
        ),
    ]
