# Generated by Django 4.2.5 on 2023-10-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_news_author_alter_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.threads', verbose_name='thread'),
        ),
    ]
