# Generated by Django 4.2.5 on 2023-10-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_replies_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.news', verbose_name='comment #'),
        ),
    ]
