# Generated by Django 4.2.5 on 2023-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_replies_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rand_id',
            field=models.TextField(default='nscpoagsl', verbose_name='nscpoagsl'),
        ),
    ]
