# Generated by Django 4.2.5 on 2023-10-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_news_rand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rand_id',
            field=models.TextField(verbose_name='da39a3ee5'),
        ),
    ]
