# Generated by Django 4.2.5 on 2023-10-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_news_rand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rand_id',
            field=models.TextField(default='da39a3ee5', verbose_name='rand_id'),
        ),
    ]
