# Generated by Django 4.2.5 on 2023-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_news_rand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='rand_id',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='rand_id'),
        ),
    ]
