# Generated by Django 4.2.5 on 2023-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_replies_rand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images', verbose_name='img'),
        ),
    ]
